[package]
name = "oxidize-postal"
version = "0.1.1"
edition = "2024"

[lib]
name = "oxidize_postal"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25", features = ["extension-module"] }
libpostal-rust = "0.1.1"
serde = "1.0"
serde_json = "1.0"
once_cell = "1.19"